Feature/add word form
JudithRe/capstone-flashcard-dictionary pull request #8
Opened 2023-08-01 14:16 UTC by JudithRe

- Created /add page with the "AddEntryForm" Component (Used Entries container to be able to display changes in wordlist (currently still with useState))
- "handleSubmitForm" function receives form data and passes it on to "handleAddEntry" function
- Added "wanakana" for immediate conversion to JP letters in JP input field
- Added "handleAddEntry" function and useState (will be replaced with db later on) in _app.js

2023-08-01 15:03 UTC, CJAkkuec requested changes
Looking good! Just some small notes here and there, but very good progress overall!

2023-08-01 15:03 UTC, CJAkkuec commented on components/AddEntryForm/index.js
> +    event.target.enInput.focus();
```suggestion
    event.preventDefault();
    const form = event.target;

    const formData = new FormData(form);
    const newEntry = Object.fromEntries(formData);

    handleAddEntry({ newEntry });

    form.reset();
    form.enInput.focus();
```
 I feel like this might add just a smidge of readability.

2023-08-01 15:03 UTC, CJAkkuec commented on components/AddEntryForm/index.js
> +              event.target.value = wanakana.toKana(event.target.value); //To change input to JP Characters directly
Perhaps this could be outsourced to a function?

2023-08-01 15:03 UTC, CJAkkuec commented on components/AddEntryForm/index.js
> +          <input type="text" id="enInput" name="enInput" required />
You may benefit from verbose naming standards, such as `id="english-input` and `name="englishInput"`.

2023-08-01 15:03 UTC, CJAkkuec commented on components/AddEntryForm/index.js
> +              event.target.value = wanakana.toKana(event.target.value); //To change input to JP Characters directly
See above. :)

2023-08-01 15:03 UTC, CJAkkuec commented on components/AddEntryForm/index.js
> +  }
I'd probably suggest - very gently - that nested type selectors are not what I'd consider best practice.

2023-08-01 15:03 UTC, CJAkkuec commented on components/StyledComponents/StyledCard.js
> +const { styled } = require("styled-components");
```suggestion
import { styled } from "styled-components";
```
Get out, require! Shoo!

2023-08-01 15:03 UTC, CJAkkuec commented on pages/_app.js
> +      },
I'd probably move this to something like `const newWordObject = //...` and not set the raw object immediately. 🤔

2023-08-02 08:52 UTC, moonwave99 approved these changes
LGTM!

2023-08-02 09:29 UTC, merged